### ISSUE TITLE
Exception on post: Connection timeout to host

### ISSUE THREAD

**Issue by Davewarrington** [ehendrix23/aioharmony#3]
Not sure if this has been fully merger now in to HA, an no longer tracked here, but i updated to 0.85 my elite hub and remote are on 206 . Different subnet to my Hass.io . The follwing appears in the logs during set up .. 

```
2019-01-10 17:59:25 ERROR (MainThread) [aioharmony.hubconnector] 10.12.1.49: Exception on post: Connection timeout to host http://10.12.1.49:8088/
2019-01-10 17:59:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 350, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/remote/harmony.py", line 180, in async_added_to_hass
    await self._client.connect()
  File "/usr/local/lib/python3.6/site-packages/aioharmony/harmonyapi.py", line 139, in connect
    return await self._harmony_client.connect()
  File "/usr/local/lib/python3.6/site-packages/aioharmony/harmonyclient.py", line 131, in connect
    if not await self._hub_connection.connect():
  File "/usr/local/lib/python3.6/site-packages/aioharmony/hubconnector.py", line 106, in connect
    response = await self.retrieve_hub_info()
  File "/usr/local/lib/python3.6/site-packages/aioharmony/hubconnector.py", line 341, in retrieve_hub_info
    return response.get('data')
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by ehendrix23** [comment]
The main issue seems to be that the connection to your HUB on 10.12.1.49 is timing out (first error).

That then does result in the traceback. I just fixed the issue for the traceback here but that is not going to resolve your problem in reality due to the timeout.

**Comment by ehendrix23** [comment]
It is doing a post to the hub to get 2 pieces of information it then requires to be able to initiate the connection for interacting with the HUB.

When you did this connection, did you do that from your Hass.IO or different system?

**Comment by Davewarrington** [comment]
Think I've just realized it's a routing issue between the subnets :( in one direction also ... i'll circle back. but it sure looks like it.

**Comment by ehendrix23** [comment]
Seems like this is resolved now. :-)
